sonar.projectKey=Vitorrevoredo_Biblioteca-API
sonar.organization=vitorrevoredo
sonar.host.url=https://sonarcloud.io

# Informações do projeto
sonar.projectName=Biblioteca API
sonar.projectVersion=1.0.0

# Caminho para os fontes
sonar.sources=src
sonar.tests=tests

# Exclusões de análise
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,**/database.json

# Exclusões de cobertura
sonar.coverage.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js

# Relatório de cobertura (gerado pelo Jest com lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
