name: CI - Push

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Testes e Cobertura
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes com cobertura
        run: npm test
