name: CI - Commit

on:
  push:
    branches:
      - main
      - melhoria-design-ci

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Trocar para branch específica
        run: git checkout ${{ github.ref_name }}

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar testes com cobertura
        run: npm test