name: CI - Commit

on:
  push:
    branches:
      - main
      - melhoria-design-ci

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      # Clonar repositório
      - name: Clonar repositório
        uses: actions/checkout@v4


      # Instalar Java
      - name: Configurar ambiente Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      # Instalar Maven
      - name: Configurar Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.6


      # Instalar dependências e compilar projeto
      - name: Instalar dependências e compilar
        run: mvn clean install -DskipTests


      # Executar testes
      - name: Executar testes
        run: mvn test


      # Gerar relatório de cobertura
      - name: Gerar cobertura de testes
        run: mvn jacoco:report