name: CI - Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:

      # Clonar repositório
      - name: Clonar repositório
        uses: actions/checkout@v4


      # Configurar Java
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      # Configurar Maven
      - name: Configurar Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.6


      # Instalar dependências e compilar
      - name: Instalar dependências e compilar
        run: mvn clean install -DskipTests


      # Executar testes
      - name: Executar testes
        run: mvn test


      # Verificar cobertura mínima de 90%
      - name: Verificar cobertura mínima 90%
        run: mvn jacoco:check